### ISSUE TITLE
twofactor_u2f compatibility

### ISSUE THREAD

**Issue by michib** [nextcloud/twofactor_webauthn#6]
Add compatibility to twofactor_u2f keys

**Comment by Spomky** [comment]
Hi @michib,

From my POV, this is not reallly needed. The U2F protocol is deprecated since the webauthn standard is approved. Moreover all FIDO U2F keys can be used in a FIDO2 context.

**Comment by kowalski7cc** [comment]
There is already an extension for U2F authentication, but as also stated by @Spomky, U2F is deprecated and soon Chrome will remove it.
Sources:

- https://groups.google.com/a/chromium.org/g/blink-dev/c/xHC3AtU_65A?pli=1
- https://developer.chrome.com/blog/deps-rems-95/

**Comment by My1** [comment]
sure it's deprecated (and by now even disabled behind a flag in chrome) but the issue is that people have existing registrations and stuff and having a way to seamlessly integrate that (either by adding compatiblity to this or by changing the twofactor_u2f to use webauthn instead) would be very nice.
the big problem is tho that if the twofactor_u2f extension would be changed that we'd practically have 2 of them with basically the same functionality

**Comment by michib** [comment]
Needed for the migration over to nextcloud, therefore reopening this issue.
